print("content-text:text/html\r\n\r\n")
print("<html>")
print("<head>")
print("<title>My Stock Market</title>")
print("</head>")
print("<body>")
print("<form action=AdminHome.py>")
print("<center>")
print("<table border=1>")
print("<caption><font size=7> Admin Login Form </font></caption>")
print("<tr><td>Enter Login ID</td><td><input type=text name=lid></td></tr>")
print("<tr><td>Enter Password</td><td><input type=password name=pwd></td></tr>")
print("<tr><td><input type=submit></td><td><input type= reset></td></tr>")
print("</table>")
print("</center>")
print("</form>")
print("</body>")
print("</html>")
