print("content-text:text/html\r\n\r\n")
print("<html>")
print("<head>")
print("<title>My Stock Market</title>")
print("</head>")
print("<body>")
print("<form action=UserHome.py>")
print("<center>")
print("<table border=1>")
print("<caption><font size=7>User Login Form</font></caption>")
print("<tr><td>Enter Login ID</td><td><input type=text name=ulid></td></tr>")
print("<tr><td>Enter Password</td><td><input type=password name=upwd></td></tr>")
print("<tr><td><input type=submit></td><td><input type= reset></td></tr>")
print("<tr><td><a href=UserReg.py>Register</a></td><td><a href=ForgetPassword.py>Forget Password</a></td></tr>")
print("</table>")
print("</center>")
print("</form>")
print("</body>")
print("</html>")
