import pymysql
import cgi

conn=pymysql.connect(host='localhost',user='root',password='1234',db='mystockmarket')
a=conn.cursor()

print("content-text:text/html\r\n\r\n")
print("<html>")
print("<head>")
print("<title>My Stock Market</title>")
print("</head>")
print("<body>")
print("<form action=UserReg1.py>")
print("<center>")
print("<table border=1>")
print("<caption><font size=7>User Registration </font></caption>")
print("<tr><td>Enter User First Name</td><td><input type=text name=ufnm></td></tr>")
print("<tr><td>Enter User Last Name</td><td><input type=text name=ulnm></td></tr>")
print("<tr><td>Select DOB</td><td><input type=date name=dob></td></tr>")
print("<tr><td>Select Gender</td><td><input type=radio name=g value=Male>Male<input type=radio name=g value=Female>female</td></tr>")
print("<tr><td>Enter Mobile Number</td><td><input type=number name=umno></td></tr>")
print("<tr><td>Enter Email</td><td><input type=email name=ueid></td></tr>")
print("<tr><td>Enter Aadhar Number</td><td><input type=number name=ano></td></tr>")
print("<tr><td>Upload Aadhar Card</td><td><input type=file name=ac></td></tr>")
print("<tr><td>Upload Photo</td><td><input type=file name=ph></td></tr>")
print("<tr><td>Upload Sign</td><td><input type=file name=sign></td></tr>")
print("<tr><td><input type=submit value=Reg></td><td><input type= reset></td></tr>")
print("<tr><td><a href=UserLogin.py>Login</a></td><td><a href=ForgetPwd.py>Forget Password</a></td></tr>")

print("</table>")
print("</center>")
print("</form>")
print("</body>")
print("</html>")